### ISSUE TITLE
本地测试不能上传

### ISSUE THREAD

**Issue by cnt1992** [xiaoshenge/html5demo#1]
最近也在做上传文件夹的需求，本地运行了楼主的代码并不能正常运行，请问是啥原因呢

**Comment by xiaoshenge** [comment]
fix:
You probably will have solved your problem now, but I'm posting this solution here to help others who come here with the same problem. In your js, there is a line that reads

 xhr.setRequestHeader("X_FILENAME", file.name);
but should read

 xhr.setRequestHeader("X-FILENAME", file.name);
since underscores are deprecated in later Apache releases (see also Header names with underscores ignored in php 5.5.1 / apache 2.4.6)

http://stackoverflow.com/questions/13851918/drag-and-drop-image-upload-not-working-on-server
